train_sentences = ["""
# global.columns = ID FORM LEMMA UPOS XPOS FEATS HEAD DEPREL DEPS MISC
# sent_id = fr-ud-test_00001
# text = Je sens qu'entre ça et les films de médecins et scientifiques fous que nous avons déjà vus, nous pourrions emprunter un autre chemin pour l'origine.
1	Je	il	PRON	_	Number=Sing|Person=1|PronType=Prs	2	subj	_	wordform=je
2	sens	sentir	VERB	_	Mood=Ind|Number=Sing|Person=1|Tense=Pres|VerbForm=Fin	0	root	_	_
3	qu'	que	SCONJ	_	_	2	comp:obj	_	SpaceAfter=No
4	entre	entre	ADP	_	_	21	mod	_	_
5	ça	ça	PRON	_	Gender=Masc|Number=Sing|Person=3|PronType=Dem	4	comp:obj	_	_
6	et	et	CCONJ	_	_	8	cc	_	_
7	les	le	DET	_	Definite=Def|Number=Plur|PronType=Art	8	det	_	_
8	films	film	NOUN	_	Gender=Masc|Number=Plur	5	conj	_	_
9	de	de	ADP	_	Shared=No	8	udep	_	_
10	médecins	médecin	NOUN	_	Gender=Masc|Number=Plur	9	comp:obj	_	_
11	et	et	CCONJ	_	_	12	cc	_	_
12	scientifiques	scientifique	NOUN	_	Gender=Masc|Number=Plur	10	conj	_	_
13	fous	fou	ADJ	_	Gender=Masc|Number=Plur|Shared=No	12	mod	_	_
14	que	que	PRON	_	PronType=Rel	18	comp:obj	_	_
15	nous	il	PRON	_	Number=Plur|Person=1|PronType=Prs	16	subj	_	_
16	avons	avoir	AUX	_	Mood=Ind|Number=Plur|Person=1|Shared=No|Tense=Pres|VerbForm=Fin	8	mod@relcl	_	_
17	déjà	déjà	ADV	_	_	16	mod	_	_
18	vus	voir	VERB	_	Gender=Masc|Number=Plur|Tense=Past|VerbForm=Part	16	comp:aux@tense	_	SpaceAfter=No
19	,	,	PUNCT	_	_	4	punct	_	_
20	nous	il	PRON	_	Number=Plur|Person=1|PronType=Prs	21	subj	_	_
21	pourrions	pouvoir	VERB	_	Mood=Cnd|Number=Plur|Person=1|Tense=Pres|VerbForm=Fin	3	comp:obj	_	_
22	emprunter	emprunter	VERB	_	VerbForm=Inf	21	comp:obj	_	Subject=SubjRaising
23	un	un	DET	_	Definite=Ind|Gender=Masc|Number=Sing|PronType=Art	25	det	_	_
24	autre	autre	ADJ	_	Gender=Masc|Number=Sing	25	mod	_	_
25	chemin	chemin	NOUN	_	Gender=Masc|Number=Sing	22	comp:obj	_	_
26	pour	pour	ADP	_	_	22	mod	_	_
27	l'	le	DET	_	Definite=Def|Number=Sing|PronType=Art	28	det	_	SpaceAfter=No
28	origine	origine	NOUN	_	Gender=Fem|Number=Sing	26	comp:obj	_	SpaceAfter=No
29	.	.	PUNCT	_	_	2	punct	_	_
""","""
# sent_id = fr-ud-test_00002
# text = On pourra toujours parler à propos d'Averroès de "décentrement du Sujet".
1	On	on	PRON	_	Gender=Masc|Number=Sing|Person=3|PronType=Ind	2	subj	_	wordform=on
2	pourra	pouvoir	VERB	_	Mood=Ind|Number=Sing|Person=3|Tense=Fut|VerbForm=Fin	0	root	_	_
3	toujours	toujours	ADV	_	_	2	mod	_	_
4	parler	parler	VERB	_	VerbForm=Inf	2	comp:obj	_	Subject=SubjRaising
5	à	à	ADP	_	_	4	mod	_	ExtPos=ADV|Idiom=Yes
6	propos	propos	NOUN	_	Gender=Masc|Number=Sing	5	comp:obj	_	InIdiom=Yes
7	d'	de	ADP	_	_	5	comp:obl	_	SpaceAfter=No
8	Averroès	Averroès	PROPN	_	_	7	comp:obj	_	_
9	de	de	ADP	_	_	4	comp:obl	_	_
10	"	"	PUNCT	_	_	11	punct	_	SpaceAfter=No
11	décentrement	décentrement	NOUN	_	Gender=Masc|Number=Sing	9	comp:obj	_	_
12-13	du	_	_	_	_	_	_	_	_
12	de	de	ADP	_	_	11	udep	_	_
13	le	le	DET	_	Definite=Def|Gender=Masc|Number=Sing|PronType=Art	14	det	_	_
14	Sujet	sujet	NOUN	_	Gender=Masc|Number=Sing	12	comp:obj	_	SpaceAfter=No|wordform=sujet
15	"	"	PUNCT	_	_	11	punct	_	SpaceAfter=No
16	.	.	PUNCT	_	_	2	punct	_	_
""","""# sent_id = fr-ud-test_00003
# text = « Il a été largement démontré que la population civile du territoire non autonome du Sahara occidental est l'objet de diverses atteintes aux droits humains, comme la détention arbitraire, les coups et les tortures », écrit l'ONG internationale, implantée dans 35 pays, citée par l'agence de presse sahraouie.
1	«	«	PUNCT	_	_	3	punct	_	_
2	Il	il	PRON	_	Gender=Masc|Number=Sing|Person=3|PronType=Prs	3	subj@expl	_	wordform=il
3	a	avoir	AUX	_	Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin	0	root	_	_
4	été	être	AUX	_	Gender=Masc|Number=Sing|Tense=Past|VerbForm=Part	3	comp:aux@tense	_	_
5	largement	largement	ADV	_	_	6	mod	_	_
6	démontré	démontrer	VERB	_	Gender=Masc|Number=Sing|Tense=Past|VerbForm=Part	4	comp:aux@pass	_	_
7	que	que	SCONJ	_	_	6	comp:obj@pass	_	_
8	la	le	DET	_	Definite=Def|Gender=Fem|Number=Sing|PronType=Art	9	det	_	_
9	population	population	NOUN	_	Gender=Fem|Number=Sing	20	subj	_	_
10	civile	civil	ADJ	_	Gender=Fem|Number=Sing	9	mod	_	_
11-12	du	_	_	_	_	_	_	_	_
11	de	de	ADP	_	_	9	udep	_	_
12	le	le	DET	_	Definite=Def|Gender=Masc|Number=Sing|PronType=Art	13	det	_	_
13	territoire	territoire	NOUN	_	Gender=Masc|Number=Sing	11	comp:obj	_	_
14	non	non	ADV	_	Polarity=Neg	15	mod	_	_
15	autonome	autonome	ADJ	_	Gender=Masc|Number=Sing	13	mod	_	_
16-17	du	_	_	_	_	_	_	_	_
16	de	de	ADP	_	_	13	udep	_	_
17	le	le	DET	_	Definite=Def|Gender=Masc|Number=Sing|PronType=Art	18	det	_	_
18	Sahara	Sahara	PROPN	_	Gender=Masc|Number=Sing	16	comp:obj	_	_
19	occidental	occidental	ADJ	_	Gender=Masc|Number=Sing	18	mod	_	_
20	est	être	AUX	_	Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin	7	comp:obj	_	_
21	l'	le	DET	_	Definite=Def|Number=Sing|PronType=Art	22	det	_	SpaceAfter=No
22	objet	objet	NOUN	_	Gender=Masc|Number=Sing	20	comp:pred	_	_
23	de	de	ADP	_	_	22	udep	_	_
24	diverses	divers	ADJ	_	Gender=Fem|Number=Plur	25	mod	_	_
25	atteintes	atteinte	NOUN	_	Gender=Fem|Number=Plur	23	comp:obj	_	_
26-27	aux	_	_	_	_	_	_	_	_
26	à	à	ADP	_	_	25	udep	_	_
27	les	le	DET	_	Definite=Def|Number=Plur|PronType=Art	28	det	_	_
28	droits	droit	NOUN	_	Gender=Masc|Number=Plur	26	comp:obj	_	_
29	humains	humain	ADJ	_	Gender=Masc|Number=Plur	28	mod	_	SpaceAfter=No
30	,	,	PUNCT	_	_	31	punct	_	_
31	comme	comme	ADP	_	_	25	udep	_	_
32	la	le	DET	_	Definite=Def|Gender=Fem|Number=Sing|PronType=Art|Shared=No	33	det	_	_
33	détention	détention	NOUN	_	Gender=Fem|Number=Sing	31	comp:obj	_	_
34	arbitraire	arbitraire	ADJ	_	Gender=Fem|Number=Sing	33	mod	_	SpaceAfter=No
35	,	,	PUNCT	_	_	37	punct	_	_
36	les	le	DET	_	Definite=Def|Number=Plur|PronType=Art	37	det	_	_
37	coups	coup	NOUN	_	Gender=Masc|Number=Plur	33	conj	_	_
38	et	et	CCONJ	_	_	40	cc	_	_
39	les	le	DET	_	Definite=Def|Number=Plur|PronType=Art	40	det	_	_
40	tortures	torture	NOUN	_	Gender=Fem|Number=Plur	37	conj	_	_
41	»	»	PUNCT	_	_	3	punct	_	SpaceAfter=No
42	,	,	PUNCT	_	_	3	punct	_	_
43	écrit	écrire	VERB	_	Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin	3	parataxis	_	_
44	l'	le	DET	_	Definite=Def|Number=Sing|PronType=Art	45	det	_	SpaceAfter=No
45	ONG	ONG	NOUN	_	Gender=Fem|Number=Sing	43	subj	_	_
46	internationale	international	ADJ	_	Gender=Fem|Number=Sing	45	mod	_	SpaceAfter=No
47	,	,	PUNCT	_	Shared=Yes	48	punct	_	_
48	implantée	implanter	VERB	_	Gender=Fem|Number=Sing|Tense=Past|VerbForm=Part	45	mod	_	_
49	dans	dans	ADP	_	_	48	comp:obl	_	_
50	35	35	NUM	_	Number=Plur	51	det	_	_
51	pays	pays	NOUN	_	Gender=Masc|Number=Plur	49	comp:obj	_	SpaceAfter=No
52	,	,	PUNCT	_	_	53	punct	_	_
53	citée	citer	VERB	_	Gender=Fem|Number=Sing|Tense=Past|VerbForm=Part	48	conj	_	_
54	par	par	ADP	_	Shared=No	53	comp:obl@agent	_	_
55	l'	le	DET	_	Definite=Def|Number=Sing|PronType=Art	56	det	_	SpaceAfter=No
56	agence	agence	NOUN	_	Gender=Fem|Number=Sing	54	comp:obj	_	_
57	de	de	ADP	_	_	56	udep	_	_
58	presse	presse	NOUN	_	Gender=Fem|Number=Sing	57	comp:obj	_	_
59	sahraouie	sahraoui	ADJ	_	Gender=Fem|Number=Sing	56	mod	_	SpaceAfter=No
60	.	.	PUNCT	_	_	3	punct	_	_
"""] * 10